---
kind: pipeline
type: docker
name: default

steps:
  # Drone does not pull git tags by default
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  # Test the app
  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go test -cover -race -v ./...

  # Make sure we can build
  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go build
      - go clean

  # Run GoReleaser only on tags
  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl --location --silent https://git.io/goreleaser | bash
    when:
      event: tag

# Preserve dependencies between steps
volumes:
  - name: deps
    temp: {}
